In [1]:
import pandas as pd 

store_sales = pd.read_csv(r'C:\Users\Admin\OneDrive\Documents\Pandas - Problem Solving - DeepSeek\Pandas---Problem-Solving---DeepSeek\Data Sets\store_sales_2024.csv')

# Dataset: "Store Sales Q1 2024"
# File name: store_sales_2024.csv

# Description:

This dataset contains quarterly sales records for a chain of ten retail stores across five regions. Each store sells products from five categories. The dataset has 50 rows and is designed to give you plenty of data to practice sorting, reindexing, iteration, concatenation, statistical functions, text operations, function application, window functions, aggregations, merging, and display options.

# Pandas – Data Handling: Practice Set 1 (Easy)
# Instructions:

* Save the dataset as store_sales_2024.csv in your working directory.

* Write the Pandas code for each task to produce the exact terminal output shown.

* Compare your output with the expected output to verify your solution.

Problem 1 – Sort the DataFrame by a Single Column
Task:
Read the CSV file into a DataFrame named df. Sort the DataFrame by the revenue column in descending order and print the first five rows.

Pandas Concept Used:
DataFrame.sort_values(by=column, ascending=False)

# Expected Output (terminal):
   store_id    store_name   region product_category  units_sold  price_per_unit  revenue   sale_date
38     S008   Theta Plaza     West     Electronics          38           300.0  11400.0  2024-02-23
23     S004   Delta Depot    South     Electronics          35           300.0  10500.0  2024-02-02
47     S007   Eta Traders     West     Electronics          33           300.0   9900.0  2024-03-09
19     S010  Kappa Corner  Central     Electronics          32           300.0   9600.0  2024-01-26
5      S006   Zeta Market     East     Electronics          30           300.0   9000.0  2024-01-12

In [ ]:
sort_descending = store_sales.sort_values(by = 'revenue', ascending= False)

print(sort_descending.head(5))

   store_id    store_name   region product_category  units_sold  \
37     S008   Theta Plaza     West      Electronics          38
23     S004   Delta Depot    South      Electronics          35
46     S007   Eta Traders     West      Electronics          33
19     S010  Kappa Corner  Central      Electronics          32
5      S006   Zeta Market     East      Electronics          30

    price_per_unit  revenue  sale_date
37             300    11400  2/23/2024
23             300    10500   2/2/2024
46             300     9900   3/9/2024
19             300     9600  1/26/2024
5              300     9000  1/12/2024

Problem 2 – Sort by Index in Descending Order
Task:
Sort the DataFrame by its index in descending order and print the first five rows.

Pandas Concept Used:
DataFrame.sort_index(ascending=False)

# Expected Output (terminal):
   store_id    store_name   region product_category  units_sold  price_per_unit  revenue   sale_date
49     S010  Kappa Corner  Central             Home          37            90.0   3330.0  2024-03-09
48     S009     Iota Hub  Central             Food          73            15.0   1095.0  2024-03-09
47     S007   Eta Traders     West     Electronics          33           300.0   9900.0  2024-03-09
46     S006   Zeta Market     East           Sports          58            80.0   4640.0  2024-03-09
45     S005  Epsilon Outlet    East             Home          32            90.0   2880.0  2024-03-02

In [ ]:
index_descending = store_sales.sort_index(ascending=False)
index_descending.head(5)

,store_id,store_name,region,product_category,units_sold,price_per_unit,revenue,sale_date
49,S010,Kappa Corner,Central,Home,37,90,3330,3/9/2024
48,S009,Iota Hub,Central,Food,73,15,1095,3/9/2024
47,S008,Theta Plaza,West,Clothing,58,50,2900,3/9/2024
46,S007,Eta Traders,West,Electronics,33,300,9900,3/9/2024
45,S006,Zeta Market,East,Sports,58,80,4640,3/9/2024

Problem 3 – Reindex the DataFrame with New Row Labels
Task:
Reindex the first three rows (indices 0, 1, and 2) of the DataFrame with new labels ['a', 'b', 'c'] and print the resulting DataFrame.

Pandas Concept Used:
DataFrame.reindex(index=new_index_list)

# Expected Output (terminal):
  store_id    store_name region product_category  units_sold  price_per_unit  revenue   sale_date
a     S001    Alpha Mart  North     Electronics        25.0           300.0   7500.0  2024-01-05
b     S002     Beta Shop  North        Clothing        45.0            50.0   2250.0  2024-01-05
c     S003   Gamma Store  South            Food        70.0            15.0   1050.0  2024-01-05

In [2]:
df_reindex = store_sales.iloc[0:3,:].copy()
df_reindex.index = ['a','b','c']

df_reindex

,store_id,store_name,region,product_category,units_sold,price_per_unit,revenue,sale_date
a,S001,Alpha Mart,North,Electronics,25,300,7500,1/5/2024
b,S002,Beta Shop,North,Clothing,45,50,2250,1/5/2024
c,S003,Gamma Store,South,Food,70,15,1050,1/5/2024

Problem 4 – Iterate Over Column Pairs Using items()
Task:
Iterate over the DataFrame using the items() method and print the column name and first two values for the columns store_name and region.

Pandas Concept Used:
DataFrame.items() for column‑wise iteration.

# Expected Output (terminal):
store_name
0    Alpha Mart
1     Beta Shop
Name: store_name, dtype: object

region
0    North
1    North
Name: region, dtype: object

In [8]:
for key, items in store_sales.items():
    if key in ['store_name', 'region']:
        print(key)
        print(items[:2])

store_name
0    Alpha Mart
1     Beta Shop
Name: store_name, dtype: str
region
0    North
1    North
Name: region, dtype: str

Problem 5 – Iterate Over Rows Using iterrows()
Task:
Using the iterrows() method, print the index and the store_name for each of the first three rows of the DataFrame.

Pandas Concept Used:
DataFrame.iterrows() for row‑wise iteration.

# Expected Output (terminal):
0 Alpha Mart
1 Beta Shop
2 Gamma Store

In [13]:
for r_index, row in store_sales.iterrows():
    if r_index in [0,1,2]:
        print(r_index, row['store_name'])

0 Alpha Mart
1 Beta Shop
2 Gamma Store

Problem 6 – Concatenate Two DataFrames Row‑wise
Task:
Create two DataFrames from the first 3 rows and the last 2 rows of df. Concatenate them using pd.concat() and print the resulting DataFrame.

Pandas Concept Used:
pd.concat([df1, df2]) for row‑wise concatenation.

# Expected Output (terminal):
   store_id    store_name   region product_category  units_sold  price_per_unit  revenue   sale_date
0      S001    Alpha Mart    North     Electronics          25           300.0   7500.0  2024-01-05
1      S002     Beta Shop    North        Clothing          45            50.0   2250.0  2024-01-05
2      S003   Gamma Store    South            Food          70            15.0   1050.0  2024-01-05
48     S009      Iota Hub  Central            Food          73            15.0   1095.0  2024-03-09
49     S010  Kappa Corner  Central            Home          37            90.0   3330.0  2024-03-09

In [16]:
first_3 = store_sales.head(3).copy()
last_2 = store_sales.tail(2).copy()
combined = pd.concat((first_3, last_2))

combined

,store_id,store_name,region,product_category,units_sold,price_per_unit,revenue,sale_date
0,S001,Alpha Mart,North,Electronics,25,300,7500,1/5/2024
1,S002,Beta Shop,North,Clothing,45,50,2250,1/5/2024
2,S003,Gamma Store,South,Food,70,15,1050,1/5/2024
48,S009,Iota Hub,Central,Food,73,15,1095,3/9/2024
49,S010,Kappa Corner,Central,Home,37,90,3330,3/9/2024

Problem 7 – Calculate Basic Statistical Values
Task:
Print the total revenue, mean units sold, minimum price per unit, and maximum price per unit from the DataFrame.

Pandas Concept Used:
sum(), mean(), min(), and max() descriptive statistics methods.

# Expected Output (terminal):
Total Revenue: 208230.0
Mean Units Sold: 44.4
Min Price Per Unit: 15.0
Max Price Per Unit: 300.0

In [8]:
summary = store_sales.agg({
    'revenue': 'sum',
    'units_sold': 'mean',
    'price_per_unit': ['min', 'max']
})

print(summary)

       revenue  units_sold  price_per_unit
sum   190945.0         NaN             NaN
mean       NaN       45.66             NaN
min        NaN         NaN            15.0
max        NaN         NaN           300.0

Problem 8 – Generate Descriptive Statistics with describe()
Task:
Print the descriptive statistics (count, mean, std, min, quartiles, max) for all numeric columns in the DataFrame using the describe() method.

Pandas Concept Used:
DataFrame.describe()

# Expected Output (terminal):
       units_sold  price_per_unit     revenue
count   50.000000        50.000000   50.000000
mean    44.400000        96.000000 4164.600000
std     15.496414       107.026976 2985.129655
min     20.000000        15.000000  900.000000
25%     32.750000        50.000000 2387.500000
50%     44.000000        80.000000 3345.000000
75%     54.250000        90.000000 4450.000000
max     80.000000       300.000000 11400.000000

Problem 9 – Convert Text to Uppercase
Task:
Print the store_name column converted to uppercase.

Pandas Concept Used:
Series.str.upper() for text transformation.

# Expected Output (terminal):
0      ALPHA MART
1       BETA SHOP
2     GAMMA STORE
3     DELTA DEPOT
4    EPSILON OUTLET
5     ZETA MARKET
6     ETA TRADERS
7     THETA PLAZA
8       IOTA HUB
9     KAPPA CORNER
.         ...
41      BETA SHOP
42    GAMMA STORE
43    DELTA DEPOT
44   EPSILON OUTLET
45    ZETA MARKET
46    ETA TRADERS
47    THETA PLAZA
48      IOTA HUB
49    KAPPA CORNER
Name: store_name, dtype: object

Problem 10 – Filter Rows Using a Text Condition
Task:
Print all rows where the product_category column contains the substring 'Electronics'.

Pandas Concept Used:
Series.str.contains() for text searching and filtering.

# Expected Output (terminal):
   store_id    store_name   region product_category  units_sold  price_per_unit  revenue   sale_date
0      S001    Alpha Mart    North     Electronics          25           300.0   7500.0  2024-01-05
5      S006   Zeta Market     East     Electronics          30           300.0   9000.0  2024-01-12
14     S005  Epsilon Outlet    East     Electronics          28           300.0   8400.0  2024-01-19
19     S010  Kappa Corner  Central     Electronics          32           300.0   9600.0  2024-01-26
23     S004   Delta Depot    South     Electronics          35           300.0  10500.0  2024-02-02
28     S009      Iota Hub  Central     Electronics          27           300.0   8100.0  2024-02-09
32     S003   Gamma Store    South     Electronics          22           300.0   6600.0  2024-02-16
37     S008   Theta Plaza     West     Electronics          38           300.0  11400.0  2024-02-23
41     S002     Beta Shop    North     Electronics          20           300.0   6000.0  2024-03-02
46     S007   Eta Traders     West     Electronics          33           300.0   9900.0  2024-03-09

Problem 11 – Apply a Function to a Column
Task:
Create a new column discount_price by applying a function to the price_per_unit column that reduces the price by 10% (multiply by 0.9). Print the store_name, product_category, price_per_unit, and discount_price columns for the first five rows, with discount_price rounded to 2 decimal places.

Pandas Concept Used:
DataFrame['col'].apply(func) for column‑wise function application.

# Expected Output (terminal):
   store_name product_category  price_per_unit  discount_price
0  Alpha Mart     Electronics           300.0           270.0
1   Beta Shop        Clothing            50.0            45.0
2  Gamma Store            Food            15.0            13.5
3  Delta Depot            Home            90.0            81.0
4  Epsilon Outlet        Sports            80.0            72.0

Problem 12 – Map Values to Create a New Column
Task:
Create a dictionary that maps each region to a numeric code: {'North': 1, 'South': 2, 'East': 3, 'West': 4, 'Central': 5}. Use the map() method to create a new column region_code. Print the store_name, region, and region_code columns for the first eight rows.

Pandas Concept Used:
Series.map(dictionary) for element‑wise value replacement.

# Expected Output (terminal):
     store_name   region  region_code
0    Alpha Mart    North            1
1     Beta Shop    North            1
2   Gamma Store    South            2
3   Delta Depot    South            2
4  Epsilon Outlet    East           3
5   Zeta Market     East            3
6   Eta Traders     West            4
7   Theta Plaza     West            4

Problem 13 – Calculate a Rolling Window Average
Task:
Calculate the 3‑period rolling average of the revenue column. Print only the first eight rows of the result rounded to 2 decimal places.

Pandas Concept Used:
Series.rolling(window=n).mean() for window functions.

# Expected Output (terminal):
0         NaN
1         NaN
2    3600.00
3    2000.00
4    2583.33
5    5233.33
6    4516.67
7    4158.33
Name: revenue, dtype: float64

Problem 14 – Apply Multiple Aggregations with agg()
Task:
Use the agg() method to calculate the sum, mean, and standard deviation of the units_sold column. Print the result as a Series.

Pandas Concept Used:
DataFrame.agg(func_list) or Series.agg(func_list) for multiple aggregations.

# Expected Output (terminal):
sum      2220.000000
mean       44.400000
std        15.496414
Name: units_sold, dtype: float64

Problem 15 – Check and Modify Display Options
Task:
Print the current value of the display.max_rows option. Then set it to 20 and print the new value.

Pandas Concept Used:
pd.get_option() and pd.set_option() for options and customization.

# Expected Output (terminal):
Default max rows: 60
New max rows: 20